using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using StreamingDigest.Domain;

namespace StreamingDigest.Infrastructure.Persistence.EntityFramework;

internal sealed class VideoTranscriptConfiguration : IEntityTypeConfiguration<VideoTranscript>
{
    public void Configure(EntityTypeBuilder<VideoTranscript> builder)
    {
        builder.ToTable("video_transcripts", "public");
        builder.HasKey(transcript => transcript.Id);

        builder.Property(transcript => transcript.Id).HasColumnName("id").ValueGeneratedNever();
        builder.Property(transcript => transcript.VideoId).HasColumnName("video_id");
        builder.Property(transcript => transcript.SourceType).HasColumnName("source_type").IsRequired().HasMaxLength(128);
        builder.Property(transcript => transcript.LanguageCode).HasColumnName("language_code").HasMaxLength(32);
        builder.Property(transcript => transcript.IsAutoGenerated).HasColumnName("is_auto_generated");
        builder.Property(transcript => transcript.IsActive).HasColumnName("is_active").HasDefaultValue(true);
        builder.Property(transcript => transcript.ModelName).HasColumnName("model_name").HasMaxLength(256);
        builder.Property(transcript => transcript.EngineName).HasColumnName("engine_name").HasMaxLength(256);
        builder.Property(transcript => transcript.FullTextOriginal).HasColumnName("full_text_original").IsRequired();
        builder.Property(transcript => transcript.FullTextOverride).HasColumnName("full_text_override");
        builder.Property(transcript => transcript.Confidence).HasColumnName("confidence").HasColumnType("numeric");
        builder.Property(transcript => transcript.CreatedAt).HasColumnName("created_at").HasColumnType("timestamptz").HasDefaultValueSql("CURRENT_TIMESTAMP");
        builder.Property(transcript => transcript.UpdatedAt).HasColumnName("updated_at").HasColumnType("timestamptz").HasDefaultValueSql("CURRENT_TIMESTAMP");
        builder.Ignore(transcript => transcript.RowVersion);

        builder.HasIndex(transcript => transcript.VideoId).HasDatabaseName("idx_video_transcripts_video_id");
        builder.HasIndex(transcript => transcript.VideoId)
            .HasDatabaseName("idx_video_transcripts_video_id_active")
            .IsUnique()
            .HasFilter("\"is_active\" = true");
        builder.HasOne<Video>()
            .WithMany()
            .HasForeignKey(transcript => transcript.VideoId)
            .OnDelete(DeleteBehavior.Cascade);
        builder.HasMany(transcript => transcript.Cues)
            .WithOne()
            .HasForeignKey(cue => cue.TranscriptId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
