namespace StreamingDigest.Application.Transcripts;

public sealed record CaptionFetchResult(
    string? LanguageCode,
    bool IsAutoGenerated,
    string FullText,
    IReadOnlyList<CaptionCueDto> Cues);
