using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using StreamingDigest.Domain;

namespace StreamingDigest.Application.Transcripts;

/// <summary>
/// Persists transcript ingestion results without performing the broader
/// video-unavailable state transition owned by Task 5.5.
/// </summary>
public sealed class TranscriptIngestionService(
    IStreamingDigestDbContext context,
    IYouTubeCaptionClient captionClient) : ITranscriptIngestionService
{
    public async Task<TranscriptIngestionResult> IngestAsync(Guid videoId, CancellationToken ct)
    {
        var video = await context.Videos.SingleOrDefaultAsync(candidate => candidate.Id == videoId, ct)
            ?? throw new InvalidOperationException($"Video '{videoId}' was not found.");

        var upstreamVideoId = ResolveUpstreamVideoId(video);
        var availableTracks = await captionClient.GetAvailableTracksAsync(upstreamVideoId, ct);
        var selectedTrack = SelectPreferredTrack(availableTracks);
        if (selectedTrack is null)
        {
            // Caller contract: broader "video unavailable" handling is owned elsewhere.
            // This service records transcript-level unavailability only.
            video.TranscriptStatus = "unavailable_captions";
            context.DomainEvents.Add(new DomainEvent
            {
                EventType = DomainEventTypeCatalog.RequireDefined(DomainEventTypeCatalog.TranscriptIngestFailed),
                Severity = "warning",
                EntityType = "video",
                EntityId = videoId,
                Message = $"No captions were available for video {videoId}",
                DetailsJson = JsonSerializer.Serialize(new
                {
                    VideoId = videoId,
                    Error = "no_captions_available"
                })
            });
            await context.SaveChangesAsync(ct);

            return new TranscriptIngestionResult(
                Succeeded: false,
                TranscriptId: null,
                SourceType: null,
                LanguageCode: null,
                CueCount: 0,
                ErrorMessage: "no_captions_available",
                Skipped: false);
        }

        var fetchedTrack = await captionClient.FetchTrackAsync(upstreamVideoId, selectedTrack.TrackCode, ct);
        var sourceType = fetchedTrack.IsAutoGenerated
            ? VideoTranscriptSourceTypes.YouTubeAutoCaption
            : VideoTranscriptSourceTypes.YouTubeCaption;
        var now = DateTimeOffset.UtcNow;

        await using var transaction = await context.Database.BeginTransactionAsync(ct);

        var activeTranscripts = await context.VideoTranscripts
            .Where(transcript => transcript.VideoId == videoId && transcript.IsActive)
            .ToListAsync(ct);

        foreach (var activeTranscript in activeTranscripts)
        {
            activeTranscript.IsActive = false;
        }

        var transcript = new VideoTranscript
        {
            VideoId = videoId,
            SourceType = sourceType,
            LanguageCode = fetchedTrack.LanguageCode,
            IsAutoGenerated = fetchedTrack.IsAutoGenerated,
            FullTextOriginal = fetchedTrack.FullText
        };

        foreach (var cue in fetchedTrack.Cues.OrderBy(cue => cue.Sequence))
        {
            transcript.Cues.Add(new TranscriptCue
            {
                Sequence = cue.Sequence,
                StartSeconds = cue.StartSeconds,
                EndSeconds = cue.EndSeconds,
                TextOriginal = cue.Text
            });
        }

        video.TranscriptStatus = "processed";
        video.TranscriptFetchedAt = now;

        context.VideoTranscripts.Add(transcript);
        context.DomainEvents.Add(new DomainEvent
        {
            EventType = DomainEventTypeCatalog.RequireDefined(DomainEventTypeCatalog.TranscriptIngested),
            Severity = "info",
            EntityType = "video",
            EntityId = videoId,
            Message = $"Transcript ingested for video {videoId}",
            DetailsJson = JsonSerializer.Serialize(new
            {
                TranscriptId = transcript.Id,
                SourceType = sourceType,
                fetchedTrack.LanguageCode,
                CueCount = transcript.Cues.Count
            })
        });

        await context.SaveChangesAsync(ct);
        await transaction.CommitAsync(ct);

        return new TranscriptIngestionResult(
            Succeeded: true,
            TranscriptId: transcript.Id,
            SourceType: sourceType,
            LanguageCode: fetchedTrack.LanguageCode,
            CueCount: transcript.Cues.Count,
            ErrorMessage: null,
            Skipped: false);
    }

    internal static CaptionTrackInfo? SelectPreferredTrack(IReadOnlyList<CaptionTrackInfo> tracks)
    {
        ArgumentNullException.ThrowIfNull(tracks);

        return tracks.FirstOrDefault(track => !track.IsAutoGenerated && IsEnglish(track.LanguageCode))
            ?? tracks.FirstOrDefault(track => !track.IsAutoGenerated)
            ?? tracks.FirstOrDefault();
    }

    private static bool IsEnglish(string? languageCode)
        => !string.IsNullOrWhiteSpace(languageCode)
           && (languageCode.Equals("en", StringComparison.OrdinalIgnoreCase)
               || languageCode.StartsWith("en-", StringComparison.OrdinalIgnoreCase));

    private static string ResolveUpstreamVideoId(Video video)
    {
        if (!string.IsNullOrWhiteSpace(video.YoutubeVideoId))
        {
            return video.YoutubeVideoId;
        }

        if (!string.IsNullOrWhiteSpace(video.PlatformVideoId))
        {
            return video.PlatformVideoId;
        }

        throw new InvalidOperationException($"Video '{video.Id}' is missing an upstream platform video id.");
    }
}
