using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using StreamingDigest.Application.AudioToText;
using StreamingDigest.Domain;

namespace StreamingDigest.Application.Transcripts;

/// <summary>
/// Persists transcript ingestion results without performing the broader
/// video-unavailable state transition owned by Task 5.5.
/// </summary>
public sealed class TranscriptIngestionService(
    IStreamingDigestDbContext context,
    IYouTubeCaptionClient captionClient,
    IAudioToTextProvider? audioToTextProvider = null,
    ITemporaryMediaManager? temporaryMediaManager = null,
    Func<Guid, CancellationToken, Task<string?>>? mediaFileResolver = null) : ITranscriptIngestionService
{
    private readonly IAudioToTextProvider? _audioToTextProvider = audioToTextProvider;
    private readonly ITemporaryMediaManager? _temporaryMediaManager = temporaryMediaManager;
    private readonly Func<Guid, CancellationToken, Task<string?>>? _mediaFileResolver = mediaFileResolver;

    public async Task<TranscriptIngestionResult> IngestAsync(Guid videoId, CancellationToken ct)
    {
        var video = await context.Videos.SingleOrDefaultAsync(candidate => candidate.Id == videoId, ct)
           ?? throw new InvalidOperationException($"Video '{videoId}' was not found.");

        var upstreamVideoId = ResolveUpstreamVideoId(video);
        var availableTracks = await captionClient.GetAvailableTracksAsync(upstreamVideoId, ct);
        var selectedTrack = SelectPreferredTrack(availableTracks);

        string sourceType;
        string? languageCode;
        string fullText;
        IReadOnlyList<AudioTranscriptionCueDto> cues;
        string? engineName;
        string? modelName;
        bool fallbackUsed;

        if (selectedTrack is not null)
        {
           var fetchedTrack = await captionClient.FetchTrackAsync(upstreamVideoId, selectedTrack.TrackCode, ct);
           sourceType = fetchedTrack.IsAutoGenerated
               ? VideoTranscriptSourceTypes.YouTubeAutoCaption
               : VideoTranscriptSourceTypes.YouTubeCaption;
           languageCode = fetchedTrack.LanguageCode;
           fullText = fetchedTrack.FullText;
           cues = fetchedTrack.Cues.Select(cue => new AudioTranscriptionCueDto(cue.StartSeconds, cue.EndSeconds, cue.Text)).ToArray();
           engineName = null;
           modelName = null;
           fallbackUsed = false;
        }
        else
        {
           var transcription = await TryTranscribeWithFallbackAsync(videoId, ct);
           if (transcription is not null && !string.IsNullOrWhiteSpace(transcription.FullText))
           {
               sourceType = VideoTranscriptSourceTypes.LocalWhisper;
               languageCode = transcription.Language;
               fullText = transcription.FullText;
               cues = transcription.Cues?.Select(cue => new AudioTranscriptionCueDto(cue.StartSeconds, cue.EndSeconds, cue.Text)).ToArray() ?? [];
               engineName = transcription.Engine;
               modelName = transcription.Model;
               fallbackUsed = true;
           }
           else
           {
               // Caller contract: broader "video unavailable" handling is owned elsewhere.
               // This service records transcript-level unavailability only.
               video.TranscriptStatus = "unavailable_captions";
               context.DomainEvents.Add(new DomainEvent
               {
                   EventType = DomainEventTypeCatalog.RequireDefined(DomainEventTypeCatalog.TranscriptIngestFailed),
                   Severity = "warning",
                   EntityType = "video",
                   EntityId = videoId,
                   Message = $"No captions were available for video {videoId}",
                   DetailsJson = JsonSerializer.Serialize(new
                   {
                       VideoId = videoId,
                       Error = "no_captions_available"
                   })
               });
               await context.SaveChangesAsync(ct);

               return new TranscriptIngestionResult(
                   Succeeded: false,
                   TranscriptId: null,
                   SourceType: null,
                   LanguageCode: null,
                   CueCount: 0,
                   ErrorMessage: "no_captions_available",
                   Skipped: false);
           }
        }

        var now = DateTimeOffset.UtcNow;

        await using var transaction = await context.Database.BeginTransactionAsync(ct);

        var activeTranscripts = await context.VideoTranscripts
           .Where(transcript => transcript.VideoId == videoId && transcript.IsActive)
           .ToListAsync(ct);

        var isCutover = activeTranscripts.Any(prior =>
           GetSourceTypePreference(sourceType) > GetSourceTypePreference(prior.SourceType));

        int inertCueOverrideCount = 0;
        if (isCutover)
        {
           var deactivatedIds = activeTranscripts.Select(t => t.Id).ToList();
           inertCueOverrideCount = await context.TranscriptCues
               .Where(cue => deactivatedIds.Contains(cue.TranscriptId) && cue.TextOverride != null)
               .CountAsync(ct);
        }

        foreach (var activeTranscript in activeTranscripts)
        {
           activeTranscript.IsActive = false;
        }

        var transcript = new VideoTranscript
        {
           VideoId = videoId,
           SourceType = sourceType,
           LanguageCode = languageCode,
           IsAutoGenerated = sourceType == VideoTranscriptSourceTypes.YouTubeAutoCaption,
           EngineName = engineName,
           ModelName = modelName,
           FullTextOriginal = fullText
        };

        foreach (var cue in cues.OrderBy(cue => cue.StartSeconds))
        {
           transcript.Cues.Add(new TranscriptCue
           {
               Sequence = transcript.Cues.Count + 1,
               StartSeconds = cue.StartSeconds,
               EndSeconds = cue.EndSeconds,
               TextOriginal = cue.Text
           });
        }

        video.TranscriptStatus = "processed";
        video.TranscriptFetchedAt = now;

        context.VideoTranscripts.Add(transcript);
        context.DomainEvents.Add(new DomainEvent
        {
           EventType = DomainEventTypeCatalog.RequireDefined(DomainEventTypeCatalog.TranscriptIngested),
           Severity = "info",
           EntityType = "video",
           EntityId = videoId,
           Message = $"Transcript ingested for video {videoId}",
           DetailsJson = JsonSerializer.Serialize(new
           {
               TranscriptId = transcript.Id,
               SourceType = sourceType,
               LanguageCode = languageCode,
               CueCount = transcript.Cues.Count,
               FallbackUsed = fallbackUsed
           })
        });

        if (isCutover)
        {
           context.DomainEvents.Add(new DomainEvent
           {
               EventType = DomainEventTypeCatalog.RequireDefined(DomainEventTypeCatalog.TranscriptCutoverCompleted),
               Severity = "info",
               EntityType = "video",
               EntityId = videoId,
               Message = inertCueOverrideCount == 0
                   ? $"Transcript upgraded to {sourceType} for video {videoId}."
                   : $"Transcript upgraded to {sourceType} for video {videoId}; {inertCueOverrideCount} cue override(s) on the previous transcript are now inert.",
               DetailsJson = JsonSerializer.Serialize(new
               {
                   NewTranscriptId = transcript.Id,
                   NewSourceType = sourceType,
                   InertCueOverrideCount = inertCueOverrideCount
               })
           });

           if (inertCueOverrideCount > 0)
           {
               context.DomainEvents.Add(new DomainEvent
               {
                   EventType = DomainEventTypeCatalog.RequireDefined(DomainEventTypeCatalog.TranscriptCutoverOverrideInert),
                   Severity = "warning",
                   EntityType = "video",
                   EntityId = videoId,
                   Message = $"{inertCueOverrideCount} cue override(s) became inert after transcript cutover to {sourceType} for video {videoId}.",
                   DetailsJson = JsonSerializer.Serialize(new
                   {
                       NewSourceType = sourceType,
                       InertCueOverrideCount = inertCueOverrideCount
                   })
               });
           }
        }

        await context.SaveChangesAsync(ct);
        await transaction.CommitAsync(ct);

        return new TranscriptIngestionResult(
           Succeeded: true,
           TranscriptId: transcript.Id,
           SourceType: sourceType,
           LanguageCode: languageCode,
           CueCount: transcript.Cues.Count,
           ErrorMessage: null,
           Skipped: false);
    }

    private async Task<AudioTranscriptionResult?> TryTranscribeWithFallbackAsync(Guid videoId, CancellationToken ct)
    {
        if (_audioToTextProvider is null)
        {
           return null;
        }

        var mediaFilePath = await ResolveMediaFilePathAsync(videoId, ct);
        if (string.IsNullOrWhiteSpace(mediaFilePath))
        {
           return null;
        }

        var tempMediaFilePath = mediaFilePath;
        var createdTemporaryMedia = false;
        if (_temporaryMediaManager is not null)
        {
           tempMediaFilePath = await _temporaryMediaManager.CreateTemporaryMediaAsync(mediaFilePath, ct);
           createdTemporaryMedia = true;
        }

        try
        {
           return await _audioToTextProvider.TranscribeAsync(new AudioTranscriptionRequest(tempMediaFilePath), ct);
        }
        catch (OperationCanceledException) when (ct.IsCancellationRequested)
        {
           throw;
        }
        catch (Exception)
        {
           return null;
        }
        finally
        {
           if (createdTemporaryMedia && !string.Equals(tempMediaFilePath, mediaFilePath, StringComparison.Ordinal))
           {
               try
               {
                   await _temporaryMediaManager!.DeleteTemporaryMediaAsync(tempMediaFilePath, ct);
               }
               catch (OperationCanceledException) when (ct.IsCancellationRequested)
               {
                   throw;
               }
               catch (Exception)
               {
                   // Best effort cleanup; a failed delete should not override the transcript result.
               }
           }
        }
    }

    private async Task<string?> ResolveMediaFilePathAsync(Guid videoId, CancellationToken ct)
    {
        if (_mediaFileResolver is null)
        {
           return null;
        }

        return await _mediaFileResolver(videoId, ct);
    }

    internal static CaptionTrackInfo? SelectPreferredTrack(IReadOnlyList<CaptionTrackInfo> tracks)
    {
        ArgumentNullException.ThrowIfNull(tracks);

        return tracks.FirstOrDefault(track => !track.IsAutoGenerated && IsEnglish(track.LanguageCode))
           ?? tracks.FirstOrDefault(track => !track.IsAutoGenerated)
           ?? tracks.FirstOrDefault();
    }

    private static bool IsEnglish(string? languageCode)
        => !string.IsNullOrWhiteSpace(languageCode)
           && (languageCode.Equals("en", StringComparison.OrdinalIgnoreCase)
               || languageCode.StartsWith("en-", StringComparison.OrdinalIgnoreCase));

    /// <summary>
    /// Returns a preference rank for <paramref name="sourceType"/>.
    /// Higher rank wins: <c>youtube_caption</c> (3) &gt; <c>local_whisper</c> (2)
    /// &gt; <c>youtube_auto_caption</c> (1) &gt; unknown (0).
    /// Matches the preference order in ADR-0010.
    /// </summary>
    public static int GetSourceTypePreference(string? sourceType) => sourceType switch
    {
        VideoTranscriptSourceTypes.YouTubeCaption => 3,
        VideoTranscriptSourceTypes.LocalWhisper => 2,
        VideoTranscriptSourceTypes.YouTubeAutoCaption => 1,
        _ => 0
    };

    private static string ResolveUpstreamVideoId(Video video)
    {
        if (!string.IsNullOrWhiteSpace(video.YoutubeVideoId))
        {
           return video.YoutubeVideoId;
        }

        if (!string.IsNullOrWhiteSpace(video.PlatformVideoId))
        {
           return video.PlatformVideoId;
        }

        throw new InvalidOperationException($"Video '{video.Id}' is missing an upstream platform video id.");
    }
}
