<Project Sdk="Microsoft.NET.Sdk.Worker">

<PropertyGroup>
  <TargetFramework>net10.0</TargetFramework>
  <Nullable>enable</Nullable>
  <ImplicitUsings>enable</ImplicitUsings>
  <UserSecretsId>dotnet-StreamingDigest.Worker-8c411e27-2002-467d-8335-2ab1b1c28b3b</UserSecretsId>
</PropertyGroup>

<ItemGroup>
  <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
  <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
  <PackageReference Include="Npgsql" Version="10.0.3" />
  <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.17.0" />
  <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.17.0" />
  <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.17.0" />
  <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.17.0-beta.1" />
  <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.17.0" />
</ItemGroup>

<ItemGroup>
  <ProjectReference Include="..\StreamingDigest.Application\StreamingDigest.Application.csproj" />
  <ProjectReference Include="..\StreamingDigest.Infrastructure\StreamingDigest.Infrastructure.csproj" />
  <ProjectReference Include="..\StreamingDigest.MatrixNotifier\StreamingDigest.MatrixNotifier.csproj" />
</ItemGroup>

  <ItemGroup>
    <None Update="appsettings.schema.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
