using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using StreamingDigest.Application.Transcripts;
using StreamingDigest.Domain;
using StreamingDigest.Infrastructure.Persistence.EntityFramework;

namespace StreamingDigest.UnitTests;

public sealed class TranscriptIngestionServiceTests : IDisposable
{
    private readonly SqliteConnection _connection;
    private readonly StreamingDigestDbContext _context;

    public TranscriptIngestionServiceTests()
    {
        _connection = new SqliteConnection("Data Source=:memory:");
        _connection.Open();

        var options = new DbContextOptionsBuilder<StreamingDigestDbContext>()
            .UseSqlite(_connection)
            .Options;

        _context = new StreamingDigestDbContext(options);
        _context.Database.EnsureCreated();
    }

    [Theory]
    [InlineData("en-manual", "youtube_caption")]
    [InlineData("fr-manual", "youtube_caption")]
    [InlineData("es-auto", "youtube_auto_caption")]
    public async Task IngestAsync_selects_tracks_in_priority_order(string expectedTrackCode, string expectedSourceType)
    {
        var video = await SeedVideoAsync("video-priority");
        var client = new StubCaptionClient(
            [
                new CaptionTrackInfo("es", true, "es-auto"),
                new CaptionTrackInfo("fr", false, "fr-manual"),
                new CaptionTrackInfo("en-US", false, "en-manual")
            ],
            new Dictionary<string, CaptionFetchResult>
            {
                ["en-manual"] = CreateFetchResult("en-US", false, "English transcript"),
                ["fr-manual"] = CreateFetchResult("fr", false, "French transcript"),
                ["es-auto"] = CreateFetchResult("es", true, "Spanish transcript")
            });

        if (expectedTrackCode == "fr-manual")
        {
            client.AvailableTracks.RemoveAll(track => track.TrackCode == "en-manual");
        }
        else if (expectedTrackCode == "es-auto")
        {
            client.AvailableTracks.RemoveAll(track => !track.IsAutoGenerated);
        }

        var service = new TranscriptIngestionService(_context, client);

        var result = await service.IngestAsync(video.Id, CancellationToken.None);

        Assert.True(result.Succeeded);
        Assert.Equal(expectedTrackCode, client.LastFetchedTrackCode);
        Assert.Equal(expectedSourceType, result.SourceType);
    }

    [Fact]
    public async Task IngestAsync_sets_unavailable_status_when_no_captions_are_found()
    {
        var video = await SeedVideoAsync("video-empty");
        var service = new TranscriptIngestionService(_context, new StubCaptionClient([], new Dictionary<string, CaptionFetchResult>()));

        var result = await service.IngestAsync(video.Id, CancellationToken.None);

        Assert.False(result.Succeeded);
        Assert.False(result.Skipped);
        Assert.Equal("no_captions_available", result.ErrorMessage);

        var updatedVideo = await _context.Videos.SingleAsync(candidate => candidate.Id == video.Id);
        Assert.Equal("unavailable_captions", updatedVideo.TranscriptStatus);
    }

    [Fact]
    public async Task IngestAsync_deactivates_previous_active_transcript()
    {
        var video = await SeedVideoAsync("video-cutover");
        var previousTranscript = new VideoTranscript
        {
            VideoId = video.Id,
            SourceType = VideoTranscriptSourceTypes.YouTubeCaption,
            LanguageCode = "en",
            FullTextOriginal = "Old transcript",
            IsActive = true
        };

        _context.VideoTranscripts.Add(previousTranscript);
        await _context.SaveChangesAsync();

        var service = new TranscriptIngestionService(
            _context,
            new StubCaptionClient(
                [new CaptionTrackInfo("en", false, "en-manual")],
                new Dictionary<string, CaptionFetchResult>
                {
                    ["en-manual"] = CreateFetchResult("en", false, "New transcript")
                }));

        var result = await service.IngestAsync(video.Id, CancellationToken.None);

        Assert.True(result.Succeeded);

        var transcripts = await _context.VideoTranscripts
            .AsNoTracking()
            .Where(candidate => candidate.VideoId == video.Id)
            .Select(candidate => new { candidate.Id, candidate.IsActive })
            .ToListAsync();

        Assert.Equal(2, transcripts.Count);
        Assert.False(transcripts.Single(candidate => candidate.Id == previousTranscript.Id).IsActive);
        Assert.True(transcripts.Single(candidate => candidate.Id == result.TranscriptId).IsActive);
    }

    [Fact]
    public async Task IngestAsync_sets_auto_caption_source_type_for_auto_generated_tracks()
    {
        var video = await SeedVideoAsync("video-auto");
        var service = new TranscriptIngestionService(
            _context,
            new StubCaptionClient(
                [new CaptionTrackInfo("en", true, "en-auto")],
                new Dictionary<string, CaptionFetchResult>
                {
                    ["en-auto"] = CreateFetchResult("en", true, "Auto transcript")
                }));

        var result = await service.IngestAsync(video.Id, CancellationToken.None);
        var transcript = await _context.VideoTranscripts.SingleAsync(candidate => candidate.Id == result.TranscriptId);

        Assert.Equal(VideoTranscriptSourceTypes.YouTubeAutoCaption, result.SourceType);
        Assert.Equal(VideoTranscriptSourceTypes.YouTubeAutoCaption, transcript.SourceType);
    }

    public void Dispose()
    {
        _context.Dispose();
        _connection.Dispose();
    }

    private async Task<Video> SeedVideoAsync(string platformVideoId)
    {
        var channel = new Channel
        {
            Id = Guid.NewGuid(),
            YoutubeChannelId = $"channel-{platformVideoId}",
            NameOriginal = "Test Channel",
            ProfileUrl = "https://www.youtube.com/@testchannel",
            SourceUrl = "https://www.youtube.com/channel/testchannel"
        };

        var video = new Video(Guid.NewGuid(), "Transcript Test")
        {
            ChannelId = channel.Id,
            PlatformVideoId = platformVideoId,
            YoutubeVideoId = platformVideoId,
            PlatformVideoUrl = $"https://www.youtube.com/watch?v={platformVideoId}",
            VideoUrl = $"https://www.youtube.com/watch?v={platformVideoId}",
            AuthorOriginal = "Test Author"
        };

        _context.Channels.Add(channel);
        _context.Videos.Add(video);
        await _context.SaveChangesAsync();
        return video;
    }

    private static CaptionFetchResult CreateFetchResult(string languageCode, bool isAutoGenerated, string fullText)
        => new(
            languageCode,
            isAutoGenerated,
            fullText,
            [
                new CaptionCueDto(1, 0m, 1.5m, $"{fullText} cue 1"),
                new CaptionCueDto(2, 1.5m, 3m, $"{fullText} cue 2")
            ]);

    private sealed class StubCaptionClient(
        IReadOnlyList<CaptionTrackInfo> availableTracks,
        IReadOnlyDictionary<string, CaptionFetchResult> fetchResults) : IYouTubeCaptionClient
    {
        public List<CaptionTrackInfo> AvailableTracks { get; } = availableTracks.ToList();
        public string? LastFetchedTrackCode { get; private set; }

        public Task<IReadOnlyList<CaptionTrackInfo>> GetAvailableTracksAsync(string videoId, CancellationToken ct)
            => Task.FromResult<IReadOnlyList<CaptionTrackInfo>>(AvailableTracks);

        public Task<CaptionFetchResult> FetchTrackAsync(string videoId, string trackCode, CancellationToken ct)
        {
            LastFetchedTrackCode = trackCode;
            return Task.FromResult(fetchResults[trackCode]);
        }
    }
}
