namespace StreamingDigest.Domain;

public sealed class VideoTranscript : AuditedEntity
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid VideoId { get; set; }
    public string SourceType { get; set; } = string.Empty;
    public string? LanguageCode { get; set; }
    public bool? IsAutoGenerated { get; set; }
    public bool IsActive { get; set; } = true;
    public string? ModelName { get; set; }
    public string? EngineName { get; set; }
    public string FullTextOriginal { get; set; } = string.Empty;
    public string? FullTextOverride { get; set; }
    public decimal? Confidence { get; set; }
    public ICollection<TranscriptCue> Cues { get; } = [];
}

public sealed class TranscriptCue : AuditedEntity
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid TranscriptId { get; set; }
    public int Sequence { get; set; }
    public decimal StartSeconds { get; set; }
    public decimal? EndSeconds { get; set; }
    public string TextOriginal { get; set; } = string.Empty;
    public string? TextOverride { get; set; }
}

public static class VideoTranscriptSourceTypes
{
    public const string YouTubeCaption = "youtube_caption";
    public const string YouTubeAutoCaption = "youtube_auto_caption";
    public const string LocalWhisper = "local_whisper";
}
