<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
  <TargetFramework>net10.0</TargetFramework>
  <ImplicitUsings>enable</ImplicitUsings>
  <Nullable>enable</Nullable>
</PropertyGroup>

<ItemGroup>
  <ProjectReference Include="..\StreamingDigest.Domain\StreamingDigest.Domain.csproj" />
</ItemGroup>

<ItemGroup>
  <PackageReference Include="JsonSchema.Net" Version="5.0.0" />
  <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.3" />
  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
  <PackageReference Include="Microsoft.SemanticKernel" Version="1.78.0" />
  <PackageReference Include="Npgsql" Version="10.0.3" />
</ItemGroup>

</Project>
